# Generated by Django 2.1.5 on 2019-01-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='栏目名称')),
                ('alias', models.CharField(max_length=10, unique=True, verbose_name='栏目别名')),
                ('keywords', models.CharField(max_length=10, null=True, verbose_name='关键字')),
                ('describe', models.CharField(max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
