# Generated by Django 2.1.5 on 2019-01-21 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='标题')),
                ('content', models.TextField()),
                ('keywords', models.CharField(max_length=10, null=True, verbose_name='关键字')),
                ('describe', models.CharField(max_length=255, null=True, verbose_name='描述')),
                ('tags', models.CharField(max_length=998, null=True, verbose_name='标签')),
                ('visibility', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='栏目')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
